# [keyboard]
# Keybindings section
# bindings = [
#     # Copy and Paste
#     { key = "C", mods = "Control|Shift", action = "Copy" },
#     { key = "V", mods = "Control|Shift", action = "Paste" },
#
#     # Scrollback
#     { key = "PageUp", mods = "Shift", action = "ScrollPageUp" },
#     { key = "PageDown", mods = "Shift", action = "ScrollPageDown" },
#
#     # Font resizing
#     { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
#     { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
#     { key = "Key0", mods = "Control", action = "ResetFontSize" },
#
#     # Quit
#     { key = "Q", mods = "Control|Shift", action = "Quit" },
#
#     # Spawn a new instance
#     { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
# ]

