#--------------------------------------------------
# window
#--------------------------------------------------

[window]
decorations = "Full" #"None"
# decorations = "None"
dynamic_padding = false
dynamic_title = true
opacity = 0.95
option_as_alt = "both"
startup_mode = "Windowed"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 4
y = 4
