name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get version from tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Create tar.gz and zip
        run: |
          mkdir artifacts
          tar --exclude=artifacts --exclude=.git -czvf artifacts/dotfiles-${VERSION}.tar.gz -- * .[^.]*
          zip -r artifacts/dotfiles-${VERSION}.zip * .[^.]* -x "artifacts/*" -x ".git/*"

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload tar.gz
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/dotfiles-${{ env.VERSION }}.tar.gz
          asset_name: dotfiles-${{ env.VERSION }}.tar.gz
          asset_content_type: application/gzip

      - name: Upload zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: artifacts/dotfiles-${{ env.VERSION }}.zip
          asset_name: dotfiles-${{ env.VERSION }}.zip
          asset_content_type: application/zip
